version: '3.3'

networks:
  mongoNet:
   name: mongoNet
   driver: bridge

services:
  api:
    build: .
    networks:
      - mongoNet
    restart: on-failure
    container_name: jplay-api
    image: jplay-api
    command: npm start
    ports:
      - "5050:5050"
